### ISSUE TITLE
Support reusing patterns

### ISSUE THREAD

**Issue by george-lim** [30bit/hitori#10]
Hey! Was trying out this project, and I was wondering if there was a way to reuse patterns without copy-pasting within the same expression.

For example, I have a very naive integer / float expression that looks like the following:

```
#[hitori::repeat(ge = 1)]
(|ch: char| ch.is_ascii_digit(),),
#[hitori::repeat(ge = 0, le = 1)]
(
    |ch| ch == '.',
    #[hitori::repeat(ge = 1)]
    (|ch: char| ch.is_ascii_digit(),),
),
```

But in my string, I have a lot of floats that I'm capturing, which results in a lot of duplicate code for the above. I don't think there is a way to "refactor" common patterns, or nest expressions at the moment. Any chance this could be added?

**Comment by 30bit** [comment]
Right now nesting isn't too hard to implement, considering there is [no backtracking](https://docs.rs/hitori/latest/hitori/index.html#limitations). But if backtracking was ever added, nesting wouldn't work as easily because for each expression instance you'd have to compile every nested expression as a part of it. So, nesting will probably come after backtracking.

In your example, pass the expression into [`string::find_iter`](https://docs.rs/hitori/latest/hitori/string/fn.find_iter.html) that returns an iter of [`Match`](https://docs.rs/hitori/latest/hitori/struct.Match.html)s.

Alternatively, add a top-level `repeat` and manually capture floats into expression struct's fields, accessing these fields from one of the char-testing closures. This will definitely be entertaining =). This [example](https://docs.rs/hitori-examples/latest/hitori_examples/repetitions/index.html#expression-bounds) could be useful as it demonstrates mutating expression's state, albeit with a different purpose.

**Comment by george-lim** [comment]
Gotcha. Thanks for the quick response! I think I'll just leave what I have for now since it isn't too big a deal.

Major props to you for building this btw 👍 It's niche, but Hitori is exactly what I needed for my project.

I'm building a WASM service that occasionally needs to parse strings extremely quickly. I didn't like the idea of embedding a regex engine into my app just for one pattern. The pattern I'm using is also 


I'm building a WASM service that occasionally needs to parse strings extremely quickly. The main problem with the other Regex crates is that they increase binary size by a significant amount, and the patterns aren't truly "compiled".

**Comment by george-lim** [comment]
Gotcha. Thanks for the quick response! I think I'll just leave what I have for now since it isn't too big a deal.

**Comment by 30bit** [comment]
You might be better off with [nom](https://docs.rs/nom/latest/nom/). It does the same thing, it is much more popular, doesn't require std, and uses strong type system rather than custom expression language.
